# Generated by Django 3.1.13 on 2021-07-25 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_community_project_projectvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lock_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
