# Generated by Django 3.1.13 on 2021-07-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_project_lock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvideo',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
